[colors.primary]
background = "0x11111b"
foreground = "0xeeeeff"

[colors.cursor]
text = "0xa6accd"
cursor = "0xe4f0fb"

[colors.search.matches]
foreground = "0x1b1e28"
background = "0xadd7ff"

[colors.search.focused_match]
foreground = "0x1b1e28"
background = "0xadd7ff"

[colors.selection]
text = "0xf8f8f2"
background = "0x2a2e3f"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.normal]
black = "0x1b1e28"
red = "0xd0679d"
green = "0x5de4c7"
yellow = "0xfffac2"
blue = "0x89ddff"
magenta = "0xfcc5e9"
cyan = "0xadd7ff"
white = "0xffffff"

[colors.bright]
black = "0xa6accd"
red = "0xd0679d"
green = "0x5de4c7"
yellow = "0xfffac2"
blue = "0xadd7ff"
magenta = "0xfae4fc"
cyan = "0x89ddff"
white = "0xffffff"
