general.import = [ "theme.toml" ]

[env]
TERM = "xterm-256color"

[cursor]
style = { shape = "Beam", blinking = "On" }

[font]
normal = { family = "CaskaydiaMono Nerd Font" }
bold = { family = "CaskaydiaMono Nerd Font" }
italic = { family = "CaskaydiaMono Nerd Font" }
size = 11

[window]
padding.x = 14
padding.y = 14

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" },
{ key = "Insert", mods = "Shift", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" }
]
